PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX tds: <http://www.knora.org/ontology/0103/theatre-societe#>
PREFIX kb: <http://www.knora.org/ontology/knora-base#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT
    distinct ?id 
    ?pseudonym
    (GROUP_CONCAT(distinct ?familyName  ; separator=';') as ?familyNames)
    (GROUP_CONCAT(distinct ?givenName  ; separator=';') as ?givenNames)
    ?label
WHERE {
    ?id a tds:Person .
    ?id kb:isDeleted "false"^^xsd:boolean .
    OPTIONAL {
	    ?id tds:hasPseudonym ?pseudoValue .
        ?pseudoValue kb:isDeleted "false"^^xsd:boolean .
    	?pseudoValue kb:valueHasString ?pseudonym .
    }
    OPTIONAL {
	    ?id tds:hasFamilyName ?familyValue .
        ?familyValue kb:isDeleted "false"^^xsd:boolean .
        ?familyValue kb:valueHasString ?familyName .
    }
    OPTIONAL {
	    ?id tds:hasGivenName ?givenValue .
        ?givenValue kb:isDeleted "false"^^xsd:boolean .
        ?givenValue kb:valueHasString ?givenName .
    }
    OPTIONAL {

	    ?id tds:thebrk1kg ?genderList .
        ?genderList kb:isDeleted "false"^^xsd:boolean .
        ?genderList kb:valueHasListNode ?node .
        ?node rdfs:label ?label .
    }
    # this is to select authors
    ?work a tds:Work .
    ?work tds:workHasAuthor ?id

    filter(?label = "femme"@fr)
}
group by ?id ?pseudonym ?label  
order by ?familyName
