        PREFIX theatre-societe: <http://www.knora.org/ontology/0103/theatre-societe#>
        PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
        select ?year (count(distinct ?s) as ?representations)
        where { 
	        ?s a theatre-societe:Representation .
            ?s theatre-societe:representationHasDate ?date .
            ?date knora-base:valueHasString ?dateString . 
            bind(replace(replace(replace(?dateString, '-.*', ''), 'GREGORIAN:', ''), ' .*', '') as ?year)
        }
        group by ?year
        order by ?year