PREFIX kb: <http://www.knora.org/ontology/knora-base#>
PREFIX tds: <http://www.knora.org/ontology/0103/theatre-societe#>

SELECT
    distinct ?id 
    ?name
	(sample(distinct ?coord_candidate) as ?coord) 
    (group_concat(distinct ?notice;separator=", ") as ?notices)
WHERE {
    ?id a tds:Place .
    ?id kb:isDeleted "false"^^xsd:boolean .

    OPTIONAL {
        ?id tds:placeHasName ?nameValue .
        ?nameValue kb:valueHasString ?name .
    }

    OPTIONAL {
        ?id tds:placeHasCoordinates ?coordValue .
        ?coordValue kb:isDeleted "false"^^xsd:boolean .
        ?coordValue kb:valueHasString ?coord_candidate .
    }

    OPTIONAL {
        ?id tds:placeHasNotice ?noticeValue .
        ?noticeValue kb:isDeleted "false"^^xsd:boolean .
        ?noticeValue kb:valueHasString ?notice .
    }
}
group by ?id ?name
